### PR TITLE
Added C++ resources  - Kindly Review

### PR DESCRIPTION
**Pull request by markandevansh99**
Please review and merge my PR.

### CODE REVIEW

**Comment by RaghavAwasthi** [comment]
@markandevansh99  Can you squash your commits

**Comment by markandevansh99** [comment]
How to do it?..Can you please squash the commits while merging?

**Comment by RaghavAwasthi** [comment]
Of course, I can squash and merge but I want to make Hacktoberfest a learning experience for all and It's a handy skill to learn.
You can squash the commits by rebasing your commits into one

Open GitBash install one if you don't have 

```
git clone yourforkrepourlhere
```
then

```
git rebase -i HEAD~2
```
After that in the Text Editor replace your last commit from *pick* to *squash*

Then do 
```
git push -f
```
This should successfully squash your commits.

If you face any issues feel free to ping me on gitter @iamraghavawasthi

**Comment by markandevansh99** [comment]
Squashing of commits done.

**Pull request merged**
